### ISSUE TITLE
GetMusicTotalTime and SetMusicPosition both fail (-1) for FLAC, MP3, Ogg Vorbis, and OPUS codecs

### ISSUE THREAD

**Issue by krcroft** [WohlSoft/SDL-Mixer-X#18]
I noticed that seek and get length code exists for the codecs, so was surprised that  Mix_GetMusicTotalTime and Mix_SetMusicPosition always return -1.  

> Mix_GetMusicTotalTime for audio-flac/audio02.flac is -1.000000 seconds
> Mix_GetMusicTotalTime for audio-mp3/audio02.mp3 is -1.000000 seconds
> Mix_GetMusicTotalTime for audio-vorbis/audio02.ogg is -1.000000 seconds
> Mix_GetMusicTotalTime for audio-opus/audio02.opus is -1.000000 seconds

Reproduce it with this code:
Note - add your own audio files to the track listing.

```c++
#include <SDL2/SDL.h>
#include <SDL2/SDL_mixer_ext.h>

static const char* const TRACKS[] = {
 "audio-flac/audio02.flac",
 "audio-mp3/audio02.mp3",
 "audio-vorbis/audio02.ogg",
 "audio-opus/audio02.opus",
 0
};

int main(int argc, char **argv) {
    int result = 0;

    if (SDL_Init(SDL_INIT_AUDIO) < 0) {
        printf("Failed to init SDL\n");
        exit(1);
    }

    int flags = MIX_INIT_FLAC|MIX_INIT_MP3|MIX_INIT_OGG|MIX_INIT_OPUS;
    if (flags != (result = Mix_Init(flags))) {
        printf("Could not initialize mixer (result: %d).\n", result);
        printf("Mix_Init: %s\n", Mix_GetError());
        exit(1);
    }

    Mix_OpenAudio(48000, AUDIO_S16SYS, 2, 4096);

    unsigned char i=0;
    while(TRACKS[i] != 0) {
        Mix_Music *music = Mix_LoadMUS(TRACKS[i]);
        if(music != NULL) {
            double duration = Mix_GetMusicTotalTime(music);
            printf("Mix_GetMusicTotalTime for %s is %f seconds\n", TRACKS[i], duration);
            Mix_FreeMusic(music);
        }
        else {
            printf("Failed to load track: %s, skipping", TRACKS[i]);
        }
        i++;
    }
    SDL_Quit();
    return 0;
}
```
Link with (assuming SDL2 and SDL-Mixer-X are both installed in --prefix=/usr/local):

`g++ -I/usr/local/include test.cpp `sdl2-config --libs` -lSDL2_mixer_ext -lvorbis -lFLAC -logg -lmad -lADLMIDI -lOPNMIDI -ltimidity -lmodplug -lgme -lzlib`

**Comment by Wohlstand** [comment]
Oh, I see the reason:
```
if (music_playing) {
    retval = music_internal_position_total();
} else {
    Mix_SetError("Music isn't playing");
    retval = -1.0;
}
```
You are calling this function while music is not playing. And I'll agree it's my fault... It's possible to retrieve the total length and seek even without of playing start

**Comment by Wohlstand** [comment]
Anyway, when speaking about of `SetMusicPosition`, it will have no sense until you will start music playing by Mix_PlayMusic(), otherwise the `Mix_PlayMusic()` resets the position to begin. The another idea would be automaticall turning music stream into "ON" and into "PAUSED" state, then you'll be able to resume it at wanted position

**Comment by Wohlstand** [comment]
Anyway, the functions are lacks "Mix_Music" structure will be deprecated since I have plan to provide "Multi-Musics" API to allow playing of multiple music-like streams which will allow cross-fade and making dynamical sound atmosphere with it.

For case of `Mix_SetMusicPosition` as it lacks `Mix_Music` argument, will not work until you will start playing. All other functions I have fixed and I'll push the fix after I'll test it on my end...

**Comment by krcroft** [comment]
Thanks for quickly investigating! Yes, it would be ideal to allow retrieval of the total track duration prior to playback.

Regarding setting the position, Makes sense that POS=0 when you first Load(). 

If the user then sets the position to <something else>, PlayMusic should simply honor whatever the set POS is and play from that (IMO).  Otherwise you need the work around you mentioned, which feels less intuitive.

**Comment by Wohlstand** [comment]
So, it works! :fox_face: :+1: 
```
$ LD_LIBRARY_PATH=../lib ./a.out 
Mix_GetMusicTotalTime for audio-flac/audio02.flac is 29.071383 seconds
Mix_GetMusicTotalTime for audio-mp3/audio02.mp3 is 29.126531 seconds
Mix_GetMusicTotalTime for audio-vorbis/audio02.ogg is 29.071383 seconds
Mix_GetMusicTotalTime for audio-opus/audio02.opus is 29.071396 seconds
```
Gotta to post the stuff....

> Regarding setting the position, Makes sense that POS=0 when you first Load().
If the user then sets the position to , PlayMusic should simply honor whatever the set POS is and play from that (IMO). Otherwise you need the work around you mentioned, which feels less intuitive.

Therefore I'll provide the new variant of `Mix_SetMusicPosition` function which will be equipped with `Mix_Music` argument and will be able to store the position. Otherwise, for now it's the limitation of `playing_music` pointer which was made originally in SDL Mixer and it makes troubles like this...

**Comment by Wohlstand** [comment]
So, I have sent the stuff, please test that out :fox_face: :wink:

**Comment by Wohlstand** [comment]
one note: When you built SDL Mixer X sharedly, you don't need to also link it's dependencies
```
g++ -I/usr/local/include test.cppsdl2-config --libs -lSDL2_mixer_ext
```
The only a reason when you have built the library statically and you need to link it

**Comment by krcroft** [comment]
Thanks for the link tips; and the update works like a charm!

(I'm working on replacing SDL Sound with SDL_Mixer X in Dosbox for BIN/CUE audio file playback)

> DOSBox version SVN
> Copyright 2002-2018 DOSBox Team, published under GNU GPL.
> CONFIG:Loading primary settings from config file /home/kcroft/.dosbox/dosbox-SVN.conf
> SDL:Current window pixel format: SDL_PIXELFORMAT_RGB888
> MIXER: requested 48000 Hz got 48000 Hz
> MIXER: requested 32784 format got 32784 format
> MIXER: requested 2 channels got 2 channels
> MIXER: using 4096-byte chunks
> ALSA:Client initialised [128:0]
> MIDI: Opened device:alsa
> CDROM_Image_Init: Mix_Init succeeded
> Mix_LoadMUS loaded: audio-flac/audio02.flac
> AudioFile::getLength: s=2269.560000, bytes=400350384
> AudioFile::read: Mix_PlayMusic()
> AudioFile::read: seek=31069920, to time=176.133333
> CDROM_Image_Destroy: Mix_Quit succeeded
> AudioFile::~AudioFile(): freeing track
