### ISSUE TITLE
musplay detects wma files as 2 day long imf files with garbage in them

### ISSUE THREAD

**Issue by igdegoo** [WohlSoft/SDL-Mixer-X#29]
https://streamable.com/1r2jf

not sure what else to put here

no wma files work

**Comment by Wohlstand** [comment]
WMA format is not supported, however, agree that the IMF detector is inaccurate, and I think, I'll make the detector to be better, and I have some idea...

**Comment by Wohlstand** [comment]
I have posted a fix just now, so, please get the most fresh MixerX's build from here: http://wohlsoft.ru/docs/_laboratory/_Builds/win32/ (get any MinGW release 32bit or 64-bit in dependency on what you are using)

**Comment by igdegoo** [comment]
which file do i download

**Comment by igdegoo** [comment]
ok i downloaded the latest sdl mixer x and most wmas say "MIX_LoadMus: modplug failed" something like that but the original wmas i tested with are the same (one is below)
[redmntn2.zip](https://github.com/WohlSoft/SDL-Mixer-X/files/3513481/redmntn2.zip)

**Comment by Wohlstand** [comment]
Which file?
- for 32-bit: http://wohlsoft.ru/docs/_laboratory/_Builds/win32/SDL-Mixer-X-MinGW-Release-Win32.7z
- for 64-bit: http://wohlsoft.ru/docs/_laboratory/_Builds/win32/SDL-Mixer-X-MinGW-w64-Release-x64.7z
inside, you'll find many folders, find the "SDL2_mixer_ext.dll" in the `bin/` folder

> ok i downloaded the latest sdl mixer x and most wmas say "MIX_LoadMus: modplug failed" something like that but the original wmas i tested with are the same (one is below)

Yeah, it's correct behaviour: WMA file must cause fail of loading. Why modplug noticed a failure? Because after inability to detect all known formats, libXMP and ModPlug are trying to identify one of tens of tracker formats, and then it also fails.

**Comment by igdegoo** [comment]
> * for 64-bit: http://wohlsoft.ru/docs/_laboratory/_Builds/win32/SDL-Mixer-X-MinGW-w64-Release-x64.7z

this one i just extracted the contents of the bin folder into the same folder as pge musplay exe

**Comment by Wohlstand** [comment]
> this one i just extracted the contents of the bin folder into the same folder as pge musplay exe

You did right, and instead of treating WMA file as IMF, report an error that can't open this file. (I have said that WMA is just not supported).

Anyway, I'll close the issue as the problem (instead of IMF garbage, report an error of file opening) has been solved.
