### ISSUE TITLE
Error when attempting to play .WAV files exported with the popular PS2 audio extracting program MFAudio 

### ISSUE THREAD

**Issue by TheEeveeLovers** [WohlSoft/SDL-Mixer-X#73]
I haven't got a chance to test this on the official SDL_Mixer, only Mixer_X, but I have also tested this in two different versions of pge_musplay and still ran into the problem.
The error in question:
`Couldn't read 61 bytes from WAV file`
Some investigation has led me to believe this is caused by MFAudio's signature at the end of each file, which is indeed 61 bytes long
![image](https://github.com/WohlSoft/SDL-Mixer-X/assets/35820985/f0d14e48-e24d-467f-b6ac-4deca18b0386)
Removing the signature causes the file to play fine with no issue whatsoever

Anyways, here are some files so you can test on your end:
[BASELINE](https://cdn.discordapp.com/attachments/982288109771309066/1176359426886738000/BASELINE.STR.wav?ex=656e9517&is=655c2017&hm=54e1b0592ecb06d937600366e035720e7f8109e08de0121bba0fa1a4dab484d9&)  -  [SLIPKNOT](https://cdn.discordapp.com/attachments/982288109771309066/1176359598895140954/SLIPKNOT.STR.wav?ex=656e9540&is=655c2040&hm=b6000ff59e7737aa22a59c66773e01181a18b2b18d3ccc3add27cda6756b950c&)  -  [POD](https://cdn.discordapp.com/attachments/982288109771309066/1176360708104007702/POD.STR.wav?ex=656e9648&is=655c2148&hm=1f02ef9bb912b7890043e79220ce63164ff216dca406b882a7edde1298190b40&)

**Comment by Wohlstand** [comment]
Lemme debug this thing... Looks like weird one...

**Comment by Wohlstand** [comment]
Actually, chunk has wrong size:
![Снимок экрана от 2023-11-21 07-57-29](https://github.com/WohlSoft/SDL-Mixer-X/assets/6751442/ac2be42f-8911-4fa6-b110-f1c4d5a3db10)

It asks 61 byte, but actually, there is 53 bytes written:
![Снимок экрана от 2023-11-21 07-57-38](https://github.com/WohlSoft/SDL-Mixer-X/assets/6751442/8856133f-c92c-47fb-9624-b845baf63beb)

As my debugger tells:
![Снимок экрана от 2023-11-21 07-57-55](https://github.com/WohlSoft/SDL-Mixer-X/assets/6751442/7741ee3f-e30e-4f0e-a197-33d94f4f0f3c)

So, technically, these WAV files considered being invalid because chunk size is longer than it stores actually. These files can be fixed by changing the chunk size value into correct value:
![Снимок экрана от 2023-11-21 08-01-13](https://github.com/WohlSoft/SDL-Mixer-X/assets/6751442/26cf6572-c1eb-42b4-91ee-99ef092fc8b0)

**Comment by Wohlstand** [comment]
I see, the MFAudio utility is actually very old and didn't updated for a while (I may guess, author won't fix this bug). However, I could make a workaround to don't invalidate the file when it reaches the end.

**Comment by Wohlstand** [comment]
Just now, I added a workaround, should work now.

**Comment by Wohlstand** [comment]
Closed because of no responce for long time, and because the task is already solved.
